### ISSUE TITLE
python tor/generate_tor_feed.py example_tor_feed.feed - Traceback

### ISSUE THREAD

**Issue by hogehoge989** [carbonblack/cbfeeds#27]
I got a below error:

[root@ns1 example]# python tor/generate_tor_feed.py example_tor_feed.feed
Traceback (most recent call last):
  File "tor/generate_tor_feed.py", line 12, in <module>
    from cbfeeds import CbReport
ImportError: No module named cbfeeds
[root@ns1 example]# 

[root@ns1 example]# ls
__init__.py  abuse_ch  isight  mdl  raw  stix  tor
[root@ns1 example]# 

Does anyone know how to solve the issue ?

**Comment by hogehoge989** [comment]
Step 1 : https://github.com/carbonblack/cbfeeds/blob/master/README.md

[root@localhost carbonblack]# yum install git
[root@localhost carbonblack]# git clone https://github.com/carbonblack/cbfeeds.git
[root@localhost carbonblack]# cd cbfeeds/
[root@localhost cbfeeds]# cd example/

[root@ns1 example]# python tor/generate_tor_feed.py example_tor_feed.feed
Traceback (most recent call last):
File "tor/generate_tor_feed.py", line 12, in
from cbfeeds import CbReport
ImportError: No module named cbfeeds
[root@ns1 example]#

[root@ns1 example]# ls
init.py abuse_ch isight mdl raw stix tor
[root@ns1 example]#

Does anyone know why trace back ?
